brew "fzf"
brew "git"
brew "git-extras"
brew "htop"
brew "ssh-copy-id"
brew "subliminal"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "wget"
brew "yarn"
brew "z"

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
cask_args appdir: '/Applications'

cask "alfred"
cask "balenaetcher"
cask "caption"
cask "docker"
cask "dozer"
cask "eqmac"
cask "firefox"
cask "firefox-developer-edition"
cask "forklift"
cask "google-chrome"
cask "hocus-focus"
cask "hyper"
cask "iina"
cask "imageoptim"
cask "insomniax"
cask "ip-in-menu-bar"
cask "kap"
cask "keka"
cask "macdown"
cask "maccy"
cask "minecraft"
cask "ngrok"
cask "notable"
cask "openemu-experimental"
cask "sequel-pro"
cask "slack"
cask "slate"
cask "sketch"
cask "spaceradar"
cask "spotify"
cask "sublime-merge"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code-insiders"

cask "font-dejavusansmono-nerd-font-mono"
cask "font-fantasquesansmono-nerd-font-mono"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-iosevka-nerd-font-mono"
cask "font-monoid-nerd-font-mono"

#mas 'Xcode', id: 497799835
#mas 'Trello', id: 1278508951
