brew "fzf"
brew "git"
brew "git-extras"
brew "htop"
brew "ssh-copy-id"
brew "subliminal"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "wget"
brew "yarn"
brew "z"

tap 'homebrew/cask-cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
cask_args appdir: '/Applications'

cask "alfred"
cask "docker"
cask "dozer"
cask "eqmac"
cask "firefox"
cask "firefox-developer-edition"
cask "forklift"
cask "google-chrome"
cask "hocus-focus"
cask "hyper"
cask "iina"
cask "ip-in-menu-bar"
cask "keka"
cask "minecraft"
cask "notable"
cask "openemu-experimental"
cask "slack"
cask "slate"
cask "sketch"
cask "spaceradar"
cask "spotify"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code"

cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-monoid-nerd-font-mono"
